build:
	@cd packages/prisma-db-introspection && yarn build && cd -
	@cd packages/prisma-yml && yarn build && cd -
	@cd packages/prisma-cli-engine && yarn build && cd -
	@cd packages/prisma-cli-core && yarn build && cd -
	@cd packages/prisma-cli && yarn build && cd -

